.Dd $Mdocdate$
.Dt tophat 1
.Os
.Sh NAME
.Nm tophat
.Nd a 2d game engine for Umka
.Sh SYNOPSIS
.Nm tophat
.Op Ar check
.Op Ar dir directory
.Op Ar help
.Op Ar license
.Op Ar main file
.Op Ar modsrc module
.Op Ar prof
.Op Ar silent
.Op Ar version
.Sh DESCRIPTION
Runs tophat programs.

The options are as follows:
.Bl -tag -width Ds
.It Ar check
Only report compile errors, don't run the program.
.It Ar dir Ar directory
Specify the resource directory.
.It Ar help
Show the help message.
.It Ar license
Show the license.
.It Ar main Ar file
Specify the main file.
.It Ar modsrc Ar module
Print the source of a builtin module.
.It Ar prof
Run the program with a profiler.
.It Ar silent
Don't print Umka warnings.
.It Ar version
Print the version.
