#!/bin/sh

TH_DIR=.

echo Data directory: $TH_DIR

mkdir -p ../th_wasm_data/wasm-out

FILES=""
FILES_SRC="main.um etc/roboto.ttf etc/test.png etc/logo/*.png"

for f in $FILES_SRC; do
	FILES="$FILES --preload-file $f"
done

echo Linking...
emcc -O3 --sASYNCIFY -Wall -fno-strict-aliasing -Wno-format-security\
	$TH_DIR/th_emscripten.a \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s STACK_SIZE=2MB \
	-lc \
	-lm \
	-sMIN_WEBGL_VERSION=2 \
	-s MINIFY_HTML=0 \
	-s EXPORTED_RUNTIME_METHODS=cwrap \
	-s EXPORTED_FUNCTIONS="['_malloc', '_free', '_main', '_run_playground' ]" \
	--shell-file=$TH_DIR/etc/playground.html \
	$FILES \
	-o ../th_wasm_data/wasm-out/index.html
