#!/usr/bin/env bash

Path=/usr/share/tophat

function get () {
	echo "downloading"
	curl "https://github.com/marekmaskarinec/tophat/raw/main/bin/tophat.zip" -o tophat.zip
	if [ -f "tophat.zip" ]; then
		echo "download completed"
	else
		echo "download failed"
		exit 1
	fi
}

function clean () {
	sudo rm -rf $Path
	rm -f tophat.zip
}

function setup () {
	sudo rm -rf $Path
	sudo mkdir $Path
	echo "extracting"
	sudo unzip $1 -d $Path
	if [ ! -f $Path/tophat-release ]; then
		echo "extracting failed"
		exit 1
	fi
	echo "copying"
	sudo mv $Path/tophat-release/* $Path
	sudo rm -r $Path/tophat-release
	echo "asking for version"
	echo "done"
}

function update() {
	if [ $(curl "https://github.com/marekmaskarinec/tophat/raw/main/bin/version") = $(cat $Path/version) ]; then
		echo "tophat is already up to date"
		exit 0
	fi

	get
	setup tophat.zip
}

function package() {
	if [ "$2" == "" ]; then
		echo "specify os"
		exit 1
	fi

	if [ "$3" == "" ]; then
		Name=game
	else
		Name=$3
	fi

	if [ "$2" == "linux" ]; then
		Bin=tophat-linux
	elif [ "$2" == "windows" ]; then
		Bin=tophat-win
	elif [ "$2" == "all" ]; then
		echo "packaging for linux"
		package $Name linux
		echo "packaging for windows"
		package $Name windows
		exit 0
	fi

	if [ "$Bin" == "" ]; then
		echo "invalid os specified. only windows and linux currently supported"
		exit 1
	fi

	mkdir ../$Name-$2
	mkdir ../$Name-$2/$Name.dat
	cp -r ./* ../$Name-$2/$Name.dat
	cp -r $Path/bin/$Bin ../$Name-$2/$Name
	if [ "$2" == "windows" ]; then
		cp $Path/bin/libumka.dll ../$Name-$2
	fi

	zip -r ../$Name-$2.zip ../$Name-$2
	rm -r ../$Name-$2
	mv ../$Name-$2.zip ./

	echo "done"
}

if [ "$1" == "run" ]; then
	$Path/bin/tophat-linux debug
	exit 0
fi

if [ "$1" == "package" ]; then
	package "" $2 $3
	exit 0
fi

if [ "$1" == "install" ]; then
	setup $2
	exit 0
fi

if [ "$1" == "update" ]; then
	update
	exit 0
fi

if [ "$1" == "uninstall" ]; then
	clean
	exit 0
fi

if [ "$1" == "get" ]; then
	get
	exit 0
fi

if [ "$1" == "init" ]; then
 	mkdir tophat
 	cp -r $Path/umka/* ./tophat
 	cp $Path/preset.um ./game.um
	exit 0
fi

echo "invalid arguments. usage:"
echo "run: runs the game in current directory"
echo "package [ platform ] [ game name ]: makes a package from the game in current directory"
echo "install [ package path ]: installs tophat from archive specified by path"
echo "update: checks for update. if new version is available, downloads it and installs it"
echo "uninstall: removes tophat data. this tool will stay"
echo "get: gets tophat data"

